/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LocaleApiReferenceRouteImport } from './routes/$locale.api-reference'
import { Route as LocaleAppRouteImport } from './routes/$locale.app'
import { Route as LocaleChoosePlanRouteImport } from './routes/$locale.choose-plan'
import { Route as LocaleContactRouteImport } from './routes/$locale.contact'
import { Route as LocaleCookiesRouteImport } from './routes/$locale.cookies'
import { Route as LocaleDocumentationRouteImport } from './routes/$locale.documentation'
import { Route as LocaleForgotPasswordRouteImport } from './routes/$locale.forgot-password'
import { Route as LocaleHelpRouteImport } from './routes/$locale.help'
import { Route as LocaleImageToExcelRouteImport } from './routes/$locale.image-to-excel'
import { Route as LocaleImageToPdfRouteImport } from './routes/$locale.image-to-pdf'
import { Route as LocaleImageToWordRouteImport } from './routes/$locale.image-to-word'
import { Route as LocaleInvoiceOcrRouteImport } from './routes/$locale.invoice-ocr'
import { Route as LocaleLoginRouteImport } from './routes/$locale.login'
import { Route as LocaleOcrApiRouteImport } from './routes/$locale.ocr-api'
import { Route as LocalePdfInvoiceParserRouteImport } from './routes/$locale.pdf-invoice-parser'
import { Route as LocalePdfToWordRouteImport } from './routes/$locale.pdf-to-word'
import { Route as LocalePrivacyRouteImport } from './routes/$locale.privacy'
import { Route as LocaleReceiptToExcelRouteImport } from './routes/$locale.receipt-to-excel'
import { Route as LocaleResetPasswordRouteImport } from './routes/$locale.reset-password'
import { Route as LocaleSecurityRouteImport } from './routes/$locale.security'
import { Route as LocaleSignupRouteImport } from './routes/$locale.signup'
import { Route as LocaleTermsRouteImport } from './routes/$locale.terms'
import { Route as LocaleVerifyEmailRouteImport } from './routes/$locale.verify-email'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as LocaleAppIndexRouteImport } from './routes/$locale.app.index'
import { Route as LocaleAppAdminRouteImport } from './routes/$locale.app.admin'
import { Route as LocaleAppBillingRouteImport } from './routes/$locale.app.billing'
import { Route as LocaleAppSettingsRouteImport } from './routes/$locale.app.settings'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale.blog.index'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale.blog.$slug'
import { Route as LocaleSolutionsSlugRouteImport } from './routes/$locale.solutions.$slug'
import { Route as ApiPaypalWebhookRouteImport } from './routes/api.paypal.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleApiReferenceRoute = LocaleApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppRoute = LocaleAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleChoosePlanRoute = LocaleChoosePlanRouteImport.update({
  id: '/choose-plan',
  path: '/choose-plan',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCookiesRoute = LocaleCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDocumentationRoute = LocaleDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleForgotPasswordRoute = LocaleForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleHelpRoute = LocaleHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleImageToExcelRoute = LocaleImageToExcelRouteImport.update({
  id: '/image-to-excel',
  path: '/image-to-excel',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleImageToPdfRoute = LocaleImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleImageToWordRoute = LocaleImageToWordRouteImport.update({
  id: '/image-to-word',
  path: '/image-to-word',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleInvoiceOcrRoute = LocaleInvoiceOcrRouteImport.update({
  id: '/invoice-ocr',
  path: '/invoice-ocr',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOcrApiRoute = LocaleOcrApiRouteImport.update({
  id: '/ocr-api',
  path: '/ocr-api',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePdfInvoiceParserRoute = LocalePdfInvoiceParserRouteImport.update({
  id: '/pdf-invoice-parser',
  path: '/pdf-invoice-parser',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePdfToWordRoute = LocalePdfToWordRouteImport.update({
  id: '/pdf-to-word',
  path: '/pdf-to-word',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleReceiptToExcelRoute = LocaleReceiptToExcelRouteImport.update({
  id: '/receipt-to-excel',
  path: '/receipt-to-excel',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleResetPasswordRoute = LocaleResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSecurityRoute = LocaleSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSignupRoute = LocaleSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleVerifyEmailRoute = LocaleVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAppIndexRoute = LocaleAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppAdminRoute = LocaleAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppBillingRoute = LocaleAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppSettingsRoute = LocaleAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSolutionsSlugRoute = LocaleSolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiPaypalWebhookRoute = ApiPaypalWebhookRouteImport.update({
  id: '/api/paypal/webhook',
  path: '/api/paypal/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/api-reference': typeof LocaleApiReferenceRoute
  '/$locale/app': typeof LocaleAppRouteWithChildren
  '/$locale/choose-plan': typeof LocaleChoosePlanRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/cookies': typeof LocaleCookiesRoute
  '/$locale/documentation': typeof LocaleDocumentationRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/help': typeof LocaleHelpRoute
  '/$locale/image-to-excel': typeof LocaleImageToExcelRoute
  '/$locale/image-to-pdf': typeof LocaleImageToPdfRoute
  '/$locale/image-to-word': typeof LocaleImageToWordRoute
  '/$locale/invoice-ocr': typeof LocaleInvoiceOcrRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/ocr-api': typeof LocaleOcrApiRoute
  '/$locale/pdf-invoice-parser': typeof LocalePdfInvoiceParserRoute
  '/$locale/pdf-to-word': typeof LocalePdfToWordRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/receipt-to-excel': typeof LocaleReceiptToExcelRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/security': typeof LocaleSecurityRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/verify-email': typeof LocaleVerifyEmailRoute
  '/api/contact': typeof ApiContactRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/app/admin': typeof LocaleAppAdminRoute
  '/$locale/app/billing': typeof LocaleAppBillingRoute
  '/$locale/app/settings': typeof LocaleAppSettingsRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/solutions/$slug': typeof LocaleSolutionsSlugRoute
  '/api/paypal/webhook': typeof ApiPaypalWebhookRoute
  '/$locale/app/': typeof LocaleAppIndexRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/api-reference': typeof LocaleApiReferenceRoute
  '/$locale/choose-plan': typeof LocaleChoosePlanRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/cookies': typeof LocaleCookiesRoute
  '/$locale/documentation': typeof LocaleDocumentationRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/help': typeof LocaleHelpRoute
  '/$locale/image-to-excel': typeof LocaleImageToExcelRoute
  '/$locale/image-to-pdf': typeof LocaleImageToPdfRoute
  '/$locale/image-to-word': typeof LocaleImageToWordRoute
  '/$locale/invoice-ocr': typeof LocaleInvoiceOcrRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/ocr-api': typeof LocaleOcrApiRoute
  '/$locale/pdf-invoice-parser': typeof LocalePdfInvoiceParserRoute
  '/$locale/pdf-to-word': typeof LocalePdfToWordRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/receipt-to-excel': typeof LocaleReceiptToExcelRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/security': typeof LocaleSecurityRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/verify-email': typeof LocaleVerifyEmailRoute
  '/api/contact': typeof ApiContactRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/app/admin': typeof LocaleAppAdminRoute
  '/$locale/app/billing': typeof LocaleAppBillingRoute
  '/$locale/app/settings': typeof LocaleAppSettingsRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/solutions/$slug': typeof LocaleSolutionsSlugRoute
  '/api/paypal/webhook': typeof ApiPaypalWebhookRoute
  '/$locale/app': typeof LocaleAppIndexRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/api-reference': typeof LocaleApiReferenceRoute
  '/$locale/app': typeof LocaleAppRouteWithChildren
  '/$locale/choose-plan': typeof LocaleChoosePlanRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/cookies': typeof LocaleCookiesRoute
  '/$locale/documentation': typeof LocaleDocumentationRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/help': typeof LocaleHelpRoute
  '/$locale/image-to-excel': typeof LocaleImageToExcelRoute
  '/$locale/image-to-pdf': typeof LocaleImageToPdfRoute
  '/$locale/image-to-word': typeof LocaleImageToWordRoute
  '/$locale/invoice-ocr': typeof LocaleInvoiceOcrRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/ocr-api': typeof LocaleOcrApiRoute
  '/$locale/pdf-invoice-parser': typeof LocalePdfInvoiceParserRoute
  '/$locale/pdf-to-word': typeof LocalePdfToWordRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/receipt-to-excel': typeof LocaleReceiptToExcelRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/security': typeof LocaleSecurityRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/verify-email': typeof LocaleVerifyEmailRoute
  '/api/contact': typeof ApiContactRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/app/admin': typeof LocaleAppAdminRoute
  '/$locale/app/billing': typeof LocaleAppBillingRoute
  '/$locale/app/settings': typeof LocaleAppSettingsRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/solutions/$slug': typeof LocaleSolutionsSlugRoute
  '/api/paypal/webhook': typeof ApiPaypalWebhookRoute
  '/$locale/app/': typeof LocaleAppIndexRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/api-reference'
    | '/$locale/app'
    | '/$locale/choose-plan'
    | '/$locale/contact'
    | '/$locale/cookies'
    | '/$locale/documentation'
    | '/$locale/forgot-password'
    | '/$locale/help'
    | '/$locale/image-to-excel'
    | '/$locale/image-to-pdf'
    | '/$locale/image-to-word'
    | '/$locale/invoice-ocr'
    | '/$locale/login'
    | '/$locale/ocr-api'
    | '/$locale/pdf-invoice-parser'
    | '/$locale/pdf-to-word'
    | '/$locale/privacy'
    | '/$locale/receipt-to-excel'
    | '/$locale/reset-password'
    | '/$locale/security'
    | '/$locale/signup'
    | '/$locale/terms'
    | '/$locale/verify-email'
    | '/api/contact'
    | '/$locale/'
    | '/$locale/app/admin'
    | '/$locale/app/billing'
    | '/$locale/app/settings'
    | '/$locale/blog/$slug'
    | '/$locale/solutions/$slug'
    | '/api/paypal/webhook'
    | '/$locale/app/'
    | '/$locale/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/api-reference'
    | '/$locale/choose-plan'
    | '/$locale/contact'
    | '/$locale/cookies'
    | '/$locale/documentation'
    | '/$locale/forgot-password'
    | '/$locale/help'
    | '/$locale/image-to-excel'
    | '/$locale/image-to-pdf'
    | '/$locale/image-to-word'
    | '/$locale/invoice-ocr'
    | '/$locale/login'
    | '/$locale/ocr-api'
    | '/$locale/pdf-invoice-parser'
    | '/$locale/pdf-to-word'
    | '/$locale/privacy'
    | '/$locale/receipt-to-excel'
    | '/$locale/reset-password'
    | '/$locale/security'
    | '/$locale/signup'
    | '/$locale/terms'
    | '/$locale/verify-email'
    | '/api/contact'
    | '/$locale'
    | '/$locale/app/admin'
    | '/$locale/app/billing'
    | '/$locale/app/settings'
    | '/$locale/blog/$slug'
    | '/$locale/solutions/$slug'
    | '/api/paypal/webhook'
    | '/$locale/app'
    | '/$locale/blog'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/api-reference'
    | '/$locale/app'
    | '/$locale/choose-plan'
    | '/$locale/contact'
    | '/$locale/cookies'
    | '/$locale/documentation'
    | '/$locale/forgot-password'
    | '/$locale/help'
    | '/$locale/image-to-excel'
    | '/$locale/image-to-pdf'
    | '/$locale/image-to-word'
    | '/$locale/invoice-ocr'
    | '/$locale/login'
    | '/$locale/ocr-api'
    | '/$locale/pdf-invoice-parser'
    | '/$locale/pdf-to-word'
    | '/$locale/privacy'
    | '/$locale/receipt-to-excel'
    | '/$locale/reset-password'
    | '/$locale/security'
    | '/$locale/signup'
    | '/$locale/terms'
    | '/$locale/verify-email'
    | '/api/contact'
    | '/$locale/'
    | '/$locale/app/admin'
    | '/$locale/app/billing'
    | '/$locale/app/settings'
    | '/$locale/blog/$slug'
    | '/$locale/solutions/$slug'
    | '/api/paypal/webhook'
    | '/$locale/app/'
    | '/$locale/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiPaypalWebhookRoute: typeof ApiPaypalWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/api-reference': {
      id: '/$locale/api-reference'
      path: '/api-reference'
      fullPath: '/$locale/api-reference'
      preLoaderRoute: typeof LocaleApiReferenceRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app': {
      id: '/$locale/app'
      path: '/app'
      fullPath: '/$locale/app'
      preLoaderRoute: typeof LocaleAppRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/choose-plan': {
      id: '/$locale/choose-plan'
      path: '/choose-plan'
      fullPath: '/$locale/choose-plan'
      preLoaderRoute: typeof LocaleChoosePlanRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/cookies': {
      id: '/$locale/cookies'
      path: '/cookies'
      fullPath: '/$locale/cookies'
      preLoaderRoute: typeof LocaleCookiesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/documentation': {
      id: '/$locale/documentation'
      path: '/documentation'
      fullPath: '/$locale/documentation'
      preLoaderRoute: typeof LocaleDocumentationRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/forgot-password': {
      id: '/$locale/forgot-password'
      path: '/forgot-password'
      fullPath: '/$locale/forgot-password'
      preLoaderRoute: typeof LocaleForgotPasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/help': {
      id: '/$locale/help'
      path: '/help'
      fullPath: '/$locale/help'
      preLoaderRoute: typeof LocaleHelpRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/image-to-excel': {
      id: '/$locale/image-to-excel'
      path: '/image-to-excel'
      fullPath: '/$locale/image-to-excel'
      preLoaderRoute: typeof LocaleImageToExcelRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/image-to-pdf': {
      id: '/$locale/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/$locale/image-to-pdf'
      preLoaderRoute: typeof LocaleImageToPdfRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/image-to-word': {
      id: '/$locale/image-to-word'
      path: '/image-to-word'
      fullPath: '/$locale/image-to-word'
      preLoaderRoute: typeof LocaleImageToWordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/invoice-ocr': {
      id: '/$locale/invoice-ocr'
      path: '/invoice-ocr'
      fullPath: '/$locale/invoice-ocr'
      preLoaderRoute: typeof LocaleInvoiceOcrRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/ocr-api': {
      id: '/$locale/ocr-api'
      path: '/ocr-api'
      fullPath: '/$locale/ocr-api'
      preLoaderRoute: typeof LocaleOcrApiRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/pdf-invoice-parser': {
      id: '/$locale/pdf-invoice-parser'
      path: '/pdf-invoice-parser'
      fullPath: '/$locale/pdf-invoice-parser'
      preLoaderRoute: typeof LocalePdfInvoiceParserRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/pdf-to-word': {
      id: '/$locale/pdf-to-word'
      path: '/pdf-to-word'
      fullPath: '/$locale/pdf-to-word'
      preLoaderRoute: typeof LocalePdfToWordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/receipt-to-excel': {
      id: '/$locale/receipt-to-excel'
      path: '/receipt-to-excel'
      fullPath: '/$locale/receipt-to-excel'
      preLoaderRoute: typeof LocaleReceiptToExcelRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reset-password': {
      id: '/$locale/reset-password'
      path: '/reset-password'
      fullPath: '/$locale/reset-password'
      preLoaderRoute: typeof LocaleResetPasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/security': {
      id: '/$locale/security'
      path: '/security'
      fullPath: '/$locale/security'
      preLoaderRoute: typeof LocaleSecurityRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/signup': {
      id: '/$locale/signup'
      path: '/signup'
      fullPath: '/$locale/signup'
      preLoaderRoute: typeof LocaleSignupRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/verify-email': {
      id: '/$locale/verify-email'
      path: '/verify-email'
      fullPath: '/$locale/verify-email'
      preLoaderRoute: typeof LocaleVerifyEmailRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/app/': {
      id: '/$locale/app/'
      path: '/'
      fullPath: '/$locale/app/'
      preLoaderRoute: typeof LocaleAppIndexRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/admin': {
      id: '/$locale/app/admin'
      path: '/admin'
      fullPath: '/$locale/app/admin'
      preLoaderRoute: typeof LocaleAppAdminRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/billing': {
      id: '/$locale/app/billing'
      path: '/billing'
      fullPath: '/$locale/app/billing'
      preLoaderRoute: typeof LocaleAppBillingRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/app/settings': {
      id: '/$locale/app/settings'
      path: '/settings'
      fullPath: '/$locale/app/settings'
      preLoaderRoute: typeof LocaleAppSettingsRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/solutions/$slug': {
      id: '/$locale/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/$locale/solutions/$slug'
      preLoaderRoute: typeof LocaleSolutionsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/paypal/webhook': {
      id: '/api/paypal/webhook'
      path: '/api/paypal/webhook'
      fullPath: '/api/paypal/webhook'
      preLoaderRoute: typeof ApiPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleAppRouteChildren {
  LocaleAppAdminRoute: typeof LocaleAppAdminRoute
  LocaleAppBillingRoute: typeof LocaleAppBillingRoute
  LocaleAppSettingsRoute: typeof LocaleAppSettingsRoute
  LocaleAppIndexRoute: typeof LocaleAppIndexRoute
}

const LocaleAppRouteChildren: LocaleAppRouteChildren = {
  LocaleAppAdminRoute: LocaleAppAdminRoute,
  LocaleAppBillingRoute: LocaleAppBillingRoute,
  LocaleAppSettingsRoute: LocaleAppSettingsRoute,
  LocaleAppIndexRoute: LocaleAppIndexRoute,
}

const LocaleAppRouteWithChildren = LocaleAppRoute._addFileChildren(
  LocaleAppRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleApiReferenceRoute: typeof LocaleApiReferenceRoute
  LocaleAppRoute: typeof LocaleAppRouteWithChildren
  LocaleChoosePlanRoute: typeof LocaleChoosePlanRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleCookiesRoute: typeof LocaleCookiesRoute
  LocaleDocumentationRoute: typeof LocaleDocumentationRoute
  LocaleForgotPasswordRoute: typeof LocaleForgotPasswordRoute
  LocaleHelpRoute: typeof LocaleHelpRoute
  LocaleImageToExcelRoute: typeof LocaleImageToExcelRoute
  LocaleImageToPdfRoute: typeof LocaleImageToPdfRoute
  LocaleImageToWordRoute: typeof LocaleImageToWordRoute
  LocaleInvoiceOcrRoute: typeof LocaleInvoiceOcrRoute
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleOcrApiRoute: typeof LocaleOcrApiRoute
  LocalePdfInvoiceParserRoute: typeof LocalePdfInvoiceParserRoute
  LocalePdfToWordRoute: typeof LocalePdfToWordRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleReceiptToExcelRoute: typeof LocaleReceiptToExcelRoute
  LocaleResetPasswordRoute: typeof LocaleResetPasswordRoute
  LocaleSecurityRoute: typeof LocaleSecurityRoute
  LocaleSignupRoute: typeof LocaleSignupRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleVerifyEmailRoute: typeof LocaleVerifyEmailRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleSolutionsSlugRoute: typeof LocaleSolutionsSlugRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleApiReferenceRoute: LocaleApiReferenceRoute,
  LocaleAppRoute: LocaleAppRouteWithChildren,
  LocaleChoosePlanRoute: LocaleChoosePlanRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleCookiesRoute: LocaleCookiesRoute,
  LocaleDocumentationRoute: LocaleDocumentationRoute,
  LocaleForgotPasswordRoute: LocaleForgotPasswordRoute,
  LocaleHelpRoute: LocaleHelpRoute,
  LocaleImageToExcelRoute: LocaleImageToExcelRoute,
  LocaleImageToPdfRoute: LocaleImageToPdfRoute,
  LocaleImageToWordRoute: LocaleImageToWordRoute,
  LocaleInvoiceOcrRoute: LocaleInvoiceOcrRoute,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleOcrApiRoute: LocaleOcrApiRoute,
  LocalePdfInvoiceParserRoute: LocalePdfInvoiceParserRoute,
  LocalePdfToWordRoute: LocalePdfToWordRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleReceiptToExcelRoute: LocaleReceiptToExcelRoute,
  LocaleResetPasswordRoute: LocaleResetPasswordRoute,
  LocaleSecurityRoute: LocaleSecurityRoute,
  LocaleSignupRoute: LocaleSignupRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleVerifyEmailRoute: LocaleVerifyEmailRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleSolutionsSlugRoute: LocaleSolutionsSlugRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiContactRoute: ApiContactRoute,
  ApiPaypalWebhookRoute: ApiPaypalWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
